Api key
cqframework/cql-exec-vsac pull request #11
Opened 2020-10-20 20:14 UTC by mitread

Added functions to support VSAC interaction using API Key authentication.  Added deprecation warnings to the existing VSAC functions.  Added unit tests for all the API key function interactions. Updated the README to note which functions/environment variables to use, as well as a note about the authentication deprecation.

2020-10-21 19:03 UTC, cmoesel requested changes
This looks really good.  I did a manual test as well to confirm it is working.  I pushed up that test to this branch so you can try it to (and because I think it may be helpful in the future).

I also noted a few typos and made one suggestion about possibly moving the deprecation warning.

2020-10-21 20:04 UTC, mitread commented on lib/CodeService.js
> +      return Promise.reject('Failed to download value sets since UMLS_API_KEYis not set.');
Fixed!

2020-10-21 20:04 UTC, mitread commented on test/test.js
> +            error.should.eql('Failed to download value sets since UMLS_API_KEYis not set.');
Fixed!

2020-10-21 20:06 UTC, mitread commented on lib/download-vsac.js
> +  vsacAuthWarning('downloadFromVSAC', 'downloadFromVSACWithAPIKey');
I removed the console warnings in `download-vsac` but left the `@deprecated` notice in the comments above the appropriate methods.  I added console warnings to functions you mentioned in `CodeService`

2020-10-22 18:07 UTC, cmoesel approved these changes
Looks good and works well!  Thanks for this, @mitread!

2020-10-22 18:07 UTC, merged